# Generated by Django 5.1.1 on 2024-10-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['fecha_publicacion'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelTable(
            name='comentarios',
            table='comentarios',
        ),
    ]
