# Generated by Django 5.1.1 on 2024-10-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comentarios_options_alter_comentarios_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentarios',
            table='Comentarios',
        ),
    ]
